apiVersion: config.porch.kpt.dev/v1alpha2
kind: PackageVariant
metadata:
  name: nads-my-core
  namespace: default
spec:
  upstream:
    repo: networking-blueprints
    package: network-attachment-renderer
    revision: main
  downstream:
    repo: nephio-my-core
    package: network-attachments
  adoption: adoptExisting
  packageContext:
    data:
      cluster-name: my-core
      target-namespace: free5gc
    repositoryRef:
      name: nephio-my-core
    removeLocalConfigResources: true
  injectors:
    - name: network-intents
  pipeline:
    mutators:
      - image: gcr.io/kpt-fn/apply-setters:v0.2
        configMap:
          target-cluster: my-core
          target-namespace: free5gc
      - image: gcr.io/nephio/nad-fn:v3.0.0
        configPath: nad-renderer-config.yaml
