apiVersion: config.porch.kpt.dev/v1alpha2
kind: PackageVariant
metadata:
  name: nads-my-ran
  namespace: default
spec:
  upstream:
    repo: networking-blueprints
    package: network-attachment-renderer
    revision: main
  downstream:
    repo: nephio-my-ran
    package: network-attachments
  adoption: adoptExisting
  packageContext:
    data:
      cluster-name: my-ran
      target-namespace: openairinterface
    repositoryRef:
      name: nephio-my-ran
    removeLocalConfigResources: true
  injectors:
    - name: network-intents
      # Inject the network intent ConfigMaps
  pipeline:
    mutators:
      - image: gcr.io/kpt-fn/apply-setters:v0.2
        configMap:
          target-cluster: my-ran
          target-namespace: openairinterface
      # Custom KRM function to render NADs from intents
      - image: gcr.io/nephio/nad-fn:v3.0.0
        configPath: nad-renderer-config.yaml
