apiVersion: config.porch.kpt.dev/v1alpha2
kind: PackageVariant
metadata:
  name: network-intents
  namespace: default
spec:
  upstream:
    repo: networking-blueprints
    package: network-intents
    revision: main
  downstream:
    repo: networking-blueprints  # Keep in same repo as reference
    package: network-intents-configured
  adoption: adoptExisting
  pipeline:
    mutators:
      - image: gcr.io/kpt-fn/apply-setters:v0.2
        configMap:
          # Customize for your LAN
          control-plane-range: "192.168.10.0/24"
          control-plane-gateway: "192.168.10.1"
          control-plane-vlan: "0"  # No VLAN
          user-plane-range: "192.168.20.0/24"
          user-plane-gateway: "192.168.20.1"
          user-plane-vlan: "0"  # No VLAN
          interface-name: "eth0"  # Your actual interface
          mtu: "1500"
